services:
  - type: web
    name: php-backend
    runtime: docker
    plan: free
    repo: https://github.com/upratham/UMA-V-2.git
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 80
